# Site settings
title: Weavr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:5000" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

exclude: [node_modules, Gruntfile.js, package.json, Gemfile, Gemfile.lock]
