# Site settings
title: Weavr
baseurl: "/Weavr" # the subpath of your site, e.g. /blog/
url: "http://opportunityintl.github.io" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

exclude: [node_modules, Gruntfile.js, package.json, Gemfile, Gemfile.lock]

nav:
  - title: 'Getting Started'
    url: 'docs/getting-started'
    pages:
      - title: 'Using Weavr'
        url: 'using-weavr'
  - title: 'Typography'
    url: 'docs/typography'
    pages:
      - title: 'Headings'
        url: 'headings'
      - title: 'Paragraphs and Links'
        url: 'paragraphs-and-links'
      - title: 'Horizontal Rules'
        url: 'horizontal-rules'
      - title: 'Lists'
        url: 'lists'
      - title: 'Blockquotes'
        url: 'blockquotes'
  - title: 'Layout'
    url: 'docs/layout'
    pages:
      - title: 'Grid'
        url: 'grid'
      - title: 'Containers'
        url: 'containers'
      - title: 'Viewport Height Sections'
        url: 'viewport-height-sections'
      - title: 'Margins and Padding'
        url: 'margins-and-padding'
      - title: 'Display Classes'
        url: 'display-classes'
      - title: 'Body Copy'
        url: 'body-copy'
  - title: 'Components'
    url: 'docs/components'
    pages:
      - title: 'Colors'
        url: 'colors'
      - title: 'Buttons'
        url: 'buttons'
      - title: 'Images and Videos'
        url: 'images-and-videos'
      - title: 'Image Backgrounds'
        url: 'image-backgrounds'
      - title: 'Background Overlays'
        url: 'background-overlays'
      - title: 'Tables'
        url: 'tables'
      - title: 'Forms'
        url: 'forms'
      - title: 'Logos'
        url: 'logos'
      - title: 'Icons'
        url: 'icons'
      - title: 'Loading Indicators'
        url: 'loading-indicators'
  - title: 'Libraries'
    url: 'docs/libraries'
